# Generated by Django 5.0.7 on 2024-11-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(null=True),
        ),
    ]
