# Generated by Django 5.0.7 on 2024-11-21 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
