# Generated by Django 5.0.7 on 2024-11-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_photo_image_alter_photo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
